Update to use new chaincode tests
hyperledger/fabric-contract-api-go pull request #63
Opened 2022-02-22 14:27 UTC by mbwhite

Signed-off-by: Matthew B White <whitemat@uk.ibm.com>

2022-02-23 09:49 UTC, mbwhite commented
/ci-run

2022-03-04 11:20 UTC, jt-nti requested changes
There seem to be a few tmp files, which I guess shouldn't be checked in. The tmp files seem to be related to modifying go.mod files in place, which could also ten get checked in inadvertently. I think the tests also require the fabric-samples repo and fabric binaries for the test network. All of which would be better/cleaner if the tests created a temporary directory outside the repo to run everything in. Something like, create temp directory, copy required files/chaincode from the repo modifying go.mod files on the way, clone fabric-samples into temp directory and put the fabric binaries in the right place, etc. etc.

2022-03-10 10:02 UTC, mbwhite commented on .azure-pipelines/scripts/fabric-quickly.sh
> +	if [ "$(ls -A $DIR)" ]; then
oh no... yes fixes

2022-03-10 10:03 UTC, mbwhite commented on integrationtest/features/feature-1-basic-checks.feature
> +# Copyright the Hyperledger Fabric contributors. All rights reserved.
yes.. they are now removed

2022-03-10 10:08 UTC, mbwhite commented
thanks @jt-nti 

On the temporary directory, currently the fabric-samples are extracted into a temp directory, pruned, and then copied locally. so it's just the test-network and binaries. 

Will think some more what the cleanest way to do this, as the location of the temporary directory will need to be carried through the various steps of the build....

2022-07-10 19:58 UTC, ryjones commented
@mbwhite I cherry-picked this to the tip of main

2022-07-11 15:32 UTC, jt-nti requested changes
Looks good- just some commented out code and a fabric-chaincode-integration-0.5.0.tgz tarball which it would be good to clear up

2022-07-11 15:32 UTC, jt-nti commented on ci/scripts/setup-integration-chaincode.sh
> +    # cat go.mod > tmp.go.mod
There's some commentated out code in this script which it would be good to tidy up

2022-07-19 07:16 UTC, jt-nti commented
The new test tool is ready! 🎉
https://github.com/hyperledger/fabric-test/packages/1545024

2022-07-19 10:47 UTC, jt-nti approved these changes
Just a minor typo left but seems good otherwise

2022-07-19 10:47 UTC, jt-nti commented on ci/scripts/setup-integration-chaincode.sh
> +# Note the actually committed go.mod files of the conahincode already have the
Typo

2022-07-19 10:56 UTC, jt-nti approved these changes

2022-07-19 10:56 UTC, merged